### ISSUE TITLE
Add validation of Destination Folder

### ISSUE THREAD

**Issue by PySimpleGUI** [Aboghazala/pyIDM#5]
I usually paste in things like destination folders.  It was writable before but see that it's readonly now (and thus white appearing in the window).

**Comment by Aboghazala** [comment]
I think i need to add a code to validate existence of destination folder, and will make it writable again, will put it in todo list

**Comment by Aboghazala** [comment]
destination folder now writable, code added for validating destination folder existence, and write permission 
commit 60c9aa1c2f14b52c04231720d6889edc615830a7
