### ISSUE TITLE
PyIDM ?

### ISSUE THREAD

**Issue by PySimpleGUI** [Aboghazala/pyIDM#7]
I wonder if you would get found a LOT more if your project was named so that people searching for Internet Download Manager would also get hits on your code.

Since you're a replacement for it, why not advertise that more heavily?

You could do an experiment by creating a second repository that has the same code in it, just renamed as a different .py filename and project name.

**Comment by Aboghazala** [comment]
Man, this is an awesome idea!

i will try it and see how this is going,
thanks a lot👍

**Comment by PySimpleGUI** [comment]
Awesome! I was a little afraid to suggest it as names of projects are a touchy thing, especially when someone puts in so much time.

PySimpleGUI went through a couple of name changes and logos before I found what I liked.

I think PyIDM is both open and super descriptive of what you've done.  It could easily be a hit.

**Comment by PySimpleGUI** [comment]
I see that PyIDM is available on PyPI!  This is a big thing to go grab for yourself.  

You may even be able to get the domain name if that's something you want.

What your project needs is a little marketing.  Borrowing the IDM initials and posting on Reddit about it will get you a big boost.

People searching for IDM may hit your GitHub or your site for sure if you got pyigm.com

**Comment by Aboghazala** [comment]
Just finished updating code, screenshots and rename repo to pyIDM, :))

**Comment by PySimpleGUI** [comment]
I LOVE IT!

I'll contact the applications list again if you want

I'm also adding colors for table headings now too!  I'll let you know when it's ready.  Then your windows will all perfectly match!

It's looking really good and the name is awesome.  I'm stunned it's available because it has the potential to be so huge!

**Comment by PySimpleGUI** [comment]
Post on Reddit at some point, but do not mention PySimpleGUI in the header and perhaps not at all in the text.  Let them ask.  There's a lot of haters of PySimpleGUI on Reddit so I don't want to see you get downvoted for something so cool you've made.

I would definitely post on Reddit with the next name, screenshots and maybe a GIF when you're ready.  Compared to everything else posted on r/python, then is amazing.  NOTHING gets posted that has this much functionality with a GUI.

**Comment by Aboghazala** [comment]
Cool!, i am glad you like it,

**Comment by PySimpleGUI** [comment]
Have you thought about getting the PyIDM account on GitHub?  I would grab it if I were you.  This makes it even easier for people to find you.  It's what almost all the big packages have done.  I did some time back so that it's PySimpleGUI/PySimpleGUI that people look for.  It can't hurt to own PyIDM/PyIDM in my opinion :-)   Then again, I'm a "anything worth doing's worth overdoing" person.

I think you're really onto something here.

**Comment by Aboghazala** [comment]
well, this is a good point, will try to get it 👍

**Comment by PySimpleGUI** [comment]
I've learned a thing or two about "sales" and marketing of packages / software that's running on Python 😏  It may sound sleezy or self-serving, but building something isn't enough any more.  

You do have to "market" it if you want people to use it.  It's why I wrote all those documents even though I HATE writing them.  It's an enabler. Something to make it easy.  For your stuff it's about being found just as much as it is about being really easy to use.

I was super-impressed with how you saved your settings.  I'm going to remember / use that code thank you!  It's like a "real windows program" or something, ya know?  Most people would just stick the setting in the application folder, but you did it right so that it doesn't matter where the application is running.  It could be an EXE and still finds the right settings.  Very nice work indeed!

**Comment by Aboghazala** [comment]
I really appreciate your value thoughts about sales, i think i am born to be a sales hater :)), i will consider your marketing advises, as you said  `building something isn't enough any more.`

> I was super-impressed with how you saved your settings. I'm going to remember / use that code thank you! It's like a "real windows program" or something, ya know? Most people would just stick the setting in the application folder, but you did it right so that it doesn't matter where the application is running. It could be an EXE and still finds the right settings. Very nice work indeed!

thanks a lot i am super flattered, and very happy you like it 👍

**Comment by PySimpleGUI** [comment]
Congrats on your successful Reddit post!!!!

People seem really happy with PyIDM.  Reddit is not the most welcoming of sites.  It takes a lot to impress the Python crowd and you certainly seem to have impressed them (and me too of course).

**Comment by PySimpleGUI** [comment]
Let's see if we can figure out  from your Stars when you posted on Reddit....

![image](https://user-images.githubusercontent.com/46163555/71786089-c6ea3a00-2fd5-11ea-85e2-8ca041d87f2c.png)

**Comment by pyIDM** [comment]
Thanks a lot Mike, you are really a good person
